-------------------------------SQL정리
CREATE TABLE TEST(
	TEST_CD VARCHAR(20) NOT NULL, 
	TEST_NM VARCHAR(10),
	TEST_POINT INT DEFAULT 0
);
--ALTER TABLE TEST ADD PK PRIMARY KEY TEST_CD;
ALTER TABLE TEST ADD TEST_DT DATE;
--명령어가 TABLE 에 적용되는지, COLUMN 에 적용되는지, 속성값에 적용되는지 잘 구분하고 분류별로 알아두기 
-- CTRL+K+C 주석 처리 / CTRL+K+U 주석 해제 (K와 U는 순차적으로 따로 누르기)
DROP TABLE TEST;
CREATE TABLE TEST(
	TEST_CD VARCHAR(20) NOT NULL, 
	TEST_NM VARCHAR(10),
	TEST_POINT INT DEFAULT 0,
	PRIMARY KEY (TEST_CD)
);


SELECT TEST_CD FROM TEST;
-- SELECT 뒤 컬럼명, FROM 뒤 테이블명

INSERT INTO TEST (TEST_CD, TEST_NM, TEST_POINT)
 VALUES ('10001', 'TEST_A', 20);
INSERT INTO TEST (TEST_CD, TEST_NM, TEST_POINT)
 VALUES ('10002', 'TEST_B', 30);
INSERT INTO TEST (TEST_CD, TEST_NM, TEST_POINT)
 VALUES ('10003', 'TEST_C', 40);
INSERT INTO TEST (TEST_CD, TEST_NM, TEST_POINT)
 VALUES ('10004', 'TEST_D', 50);
INSERT INTO TEST (TEST_CD, TEST_NM, TEST_POINT)
 VALUES ('10005', 'TEST_E', 60);
 -- INTO + 테이블 (컬럼명) VALUES (컬럼에 넣길 원하는 속성 값)
 -- VALUE 가 하나면 VALUE 로 써도 되지만 여러개일 경우 VALUES 라고 적어야함. 상단 컬럼명에 넣은 갯수와 문자형이 같아야한다. 

SELECT * FROM TEST;
SELECT * FROM TEST WHERE TEST_POINT = 20;

UPDATE TEST SET TEST_NM = 'TEST_Z';
-- UPDATE 의 경우 WHERE절을 적어주지 않으면 컬럼의 모든 값이 동일하게 바뀐다. 컬럼의 모든 값이 동일하게 바뀔일이 거의 없으므로 WHERE절을 꼭 써야한다고 볼 수 있다. 
UPDATE TEST SET TEST_NM = 'TEST_A' WHERE TEST_POINT = 20;
UPDATE TEST SET TEST_NM = 'TEST_B' WHERE TEST_POINT = 30;
UPDATE TEST SET TEST_NM = 'TEST_C' WHERE TEST_POINT = 40;

--DELETE는 신중하게! DELETE 역시 WHERE 절 없이 쓰는 경우가 드물다. 데이터가 날아가면 복구할 수 없으니 SELECT 로 먼저 확인해보고 DELETE 하고 WHERE 절의 조건을 잘 확인
--DELETE 실행 후에도 SELECT 통해서 맞는 데이터가 DELETE 되었는지 확인 
SELECT * FROM TEST WHERE TEST_CD = '10005';
DELETE FROM TEST WHERE TEST_CD = '10005';


CREATE TABLE TEST2 (
	TEST2_CD VARCHAR(20) NOT NULL,
	TEST2_ID VARCHAR(10) NOT NULL,
	TEST2_ADD VARCHAR(10),
	PRIMARY KEY (TEST2_CD),
	FOREIGN KEY (TEST2_CD) REFERENCES TEST(TEST_CD)
);
DROP TABLE TEST2;
SELECT * FROM TEST2;

INSERT INTO TEST2 (TEST2_CD, TEST2_ID, TEST2_ADD)
 VALUES ('10001', 'TEST_A', '전주시');
INSERT INTO TEST2 (TEST2_CD, TEST2_ID, TEST2_ADD)
 VALUES ('10002', 'TEST_B', '부산시');
INSERT INTO TEST2 (TEST2_CD, TEST2_ID, TEST2_ADD)
 VALUES ('10003', 'TEST_C', '인천시');
INSERT INTO TEST2 (TEST2_CD, TEST2_ID, TEST2_ADD)
 VALUES ('10004', 'TEST_D', '서울시');


 SELECT * FROM TEST T01 
	LEFT OUTER JOIN TEST2 T02 
	ON T01 T02;